Homework 7 Korobkina
KorobkinaDP/KorobkinaDP pull request #8
Opened 2020-12-13 23:44 UTC by KorobkinaDP

2020-12-14 13:55 UTC, MathPracticum requested changes
не нужно выводить топ слова внутри тем датасета. Нужно вывести топ слова, внутри тем, выделенных LDA, а затем попробовать дать интерпретакию, что это могла быть за тема. Это могла быть одна из тем датасета, или что-то новое

2020-12-14 17:04 UTC, KorobkinaDP commented
Добавила нужный вывод

2020-12-21 08:18 UTC, MathPracticum commented
Не увидел нужного вывода. По-прежнему печатаются по порядку список тем из датасета и топ слова LDA по теме с таким же порядковым номером. В этом нет смысла.

2020-12-25 00:28 UTC, KorobkinaDP commented
Добавила последнюю версию

2020-12-25 08:38 UTC, MathPracticum approved these changes

2020-12-25 08:41 UTC, merged